### ISSUE TITLE
[Feature]: New architecture support

### ISSUE THREAD

**Issue by TheRogue76** [braze-inc/braze-react-native-sdk#161]
Hi. Any plans for the new Architecture support?

**Comment by wesleyorbin** [comment]
Hi @TheRogue76. We have this on our radar, but do not have a timeline to share at this time. We'll keep you posted of any updates on this issue.

**Comment by macnibblet** [comment]
@wesleyorbin Any update on this? It's currently blocking us from upgrading our RN stack :(

**Comment by wesleyorbin** [comment]
Hi @adamsinnott. We can certainly add a note to the docs. However, the new architecture is still opt-in in 0.71 (confirmed by creating a new app with `npx react-native init --version 0.71.0`).

As for timeline, we are currently migrating the React Native SDK to use our new Swift SDK and will not be able to start work on the new architecture until that's completed. We will post any updates here as we have them.

**Comment by alzalabany** [comment]
hello; in v72.1 app crash once app is loaded

```
Unhandled JS Exception: TypeError: Cannot read property 'installCoreFunctions' of undefined, js engine: hermes, stack:\ninstallCoreFunctions@44401:58\ninitializeUIRuntime@45116:50\nanonymous@43901:59\nloadModuleImplementation@150
```

only way i could make it work if i remove part for setting up `Setup Braze bridge`.
yet notifications no longer works

**Comment by JohnathanWhite** [comment]
@wesleyorbin any updates on this?

**Comment by wesleyorbin** [comment]
@JohnathanWhite Work on the new architecture support is in progress. We'll post an update here when we have released support.

**Comment by JohnathanWhite** [comment]
> @JohnathanWhite Work on the new architecture is in progress. We'll post an update here when we have released support.

thanks for the update! Just so we can better plan on our side - is there a tentative release date?

**Comment by jerielng** [comment]
Hey @adamsinnott, you shouldn't run into any issues importing our SDK into a React Native app running 0.71+. Our compatibility requirements can be found in our docs [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#prerequisites-and-compatibility). In fact, our [sample app](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/package.json#L16) is currently using `0.71.2` as a base.

However, I should also note that running the New Architecture is independent of the version of React Native your app is using. If you wish to use a newer version of React Native while still running the old architecture on your app, you can:
1. set the `newArchEnabled` flag to `false` in your `gradle.properties` for Android
2. run `pod install` without the `RCT_NEW_ARCH_ENABLED=1` flag for iOS

To verify that you are still on the old architecture, you should not be seeing the `fabric` tag, as described [here](https://reactnative.dev/docs/the-new-architecture/use-app-template#confirming-the-new-architecture-is-in-use).

For more details, you can refer to this [page](https://reactnative.dev/docs/the-new-architecture/use-app-template) in the React Native documentation.

Should you run into any issues, feel free to let us know, and we can explore that together. Thanks!

**Comment by adamsinnott** [comment]
@jerielng thanks for the quick response, we'll give it a go. Thank you.

**Comment by hokstuff** [comment]
Hi all,

As mentioned above, our React Native SDK 2.0.1+ supports the New Architecture. Beginning in [version 6.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/6.0.0), the Braze bridge uses the New Architecture Turbo Module.

Since there are no further action items, I'm going to close out this issue - thanks!
