### ISSUE TITLE
[Feature]:  Braze.removeEventListener(Braze.Events.PUSH_NOTIFICATION_EVENT);

### ISSUE THREAD

**Issue by Kailash23** [braze-inc/braze-react-native-sdk#190]
### What problem are you facing?

I am not able to remove the added event listener
I need to remove the event listener when component unmounts

```
  useEffect(() => {
    Braze.addListener(Braze.Events.PUSH_NOTIFICATION_EVENT, handleDeeplinkUrl);

    return () => { 
     // Error : Property 'removeEventListener' does not exist on type 'typeof import("/Users/***/node_modules/react-native-appboy-sdk/src/index")'.
      Braze.removeEventListener(Braze.Events.PUSH_NOTIFICATION_EVENT); 
    }
  }, [handleDeeplinkUrl]);
```

### Workarounds

No workarounds

**Comment by wesleyorbin** [comment]
Hi @Kailash23. The `addListener()` function returns an `EmitterSubscription` object, which has a `remove()` method that you can call when your component unmounts.

```javascript
useEffect(() => {
  const listener = Braze.addListener(Braze.Events.PUSH_NOTIFICATION_EVENT, handleDeeplinkUrl);

  return () => { 
    listener.remove();
  }
}, [handleDeeplinkUrl]);
```

**Comment by Kailash23** [comment]
@wesleyorbin 
Please let me know if this push notification listener will also work on iOS?

**Comment by wesleyorbin** [comment]
@Kailash23 It currently only works on Android. You can follow #174 for updates.
