### ISSUE TITLE
[Feature]: React Native iOS sdk setup missing swift version of configuration

### ISSUE THREAD

**Issue by bernardorubin** [braze-inc/braze-react-native-sdk#191]
### What problem are you facing?

I'm trying to setup the react-native sdk following the documentation here:
https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#step-2-complete-native-setup

But the `AppDelegate.m` changes only come in objective c and not swift. I see you have swift in other docs but it's missing here. Tried adapting the code to swift but it doesn't work.

### Workarounds

Converting the code to Swift which I tried but doesn't really work:

```swift
func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil
) -> Bool {
    // Setup Braze bridge
    let moduleInitializer = BrazeReactBridge() as? RCTBridgeDelegate
    let bridge = RCTBridge(
        delegate: moduleInitializer,
        launchOptions: launchOptions)
    let rootView = RCTRootView(
        bridge: bridge,
        moduleName: "<YOUR_PROJECT_NAME>",
        initialProperties: nil)
    self.bridge = rootView.bridge

    // Configure views in the application
    window = UIWindow(frame: UIScreen.main.bounds)
    let rootViewController = UIViewController()
    rootViewController.view = rootView
    window.rootViewController = rootViewController
    window.makeKeyAndVisible()

    // Setup Braze
    let configuration = BRZConfiguration(
        apiKey: "<BRAZE_API_KEY>",
        endpoint: "<BRAZE_ENDPOINT>")
    // - Enable logging and customize the configuration here
    let braze = BrazeReactBridge.initBraze(configuration)
    AppDelegate.braze() = braze

    return true
}

// MARK: - AppDelegate.braze
private var _braze: Braze? = nil

class func braze() -> Braze? {
    return braze
}

class func setBraze(_ braze: Braze?) {
    self.braze = braze
}
```

### Ideal Solution

It would be nice to have the documentation updated for swift as well.

**Comment by lowip** [comment]
Hi @bernardorubin,

Thanks for reporting this issue, we'll update our documentation with the following Swift code snippet:

```swift
func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil
) -> Bool {
    // Setup Braze bridge
    let moduleInitializer = BrazeReactBridge() as? RCTBridgeDelegate
    let bridge = RCTBridge(
        delegate: moduleInitializer,
        launchOptions: launchOptions)
    let rootView = RCTRootView(
        bridge: bridge,
        moduleName: "<YOUR_PROJECT_NAME>",
        initialProperties: nil)
    self.bridge = rootView.bridge

    // Configure views in the application
    window = UIWindow(frame: UIScreen.main.bounds)
    let rootViewController = UIViewController()
    rootViewController.view = rootView
    window.rootViewController = rootViewController
    window.makeKeyAndVisible()

    // Setup Braze
    let configuration = Braze.Configuration(
        apiKey: "<BRAZE_API_KEY>",
        endpoint: "<BRAZE_ENDPOINT>")
    // - Enable logging and customize the configuration here
    let braze = BrazeReactBridge.initBraze(configuration)
    AppDelegate.braze = braze

    return true
}

// MARK: - AppDelegate.braze
static var braze: Braze? = nil
```

**Comment by bernardorubin** [comment]
Thanks @hokstuff 🙏

**Comment by hokstuff** [comment]
Hi @bernardorubin,

- The file is unable to find `BrazeReactBridge` because you need to import the bridge into your file, which is what this line does [in the sample app](https://github.com/braze-inc/braze-react-native-sdk/blob/0fc74254b448d3d8ef10d37fbcd877a6b55909e4/BrazeProject/ios/BrazeProject/AppDelegate.mm#L8). The snippet is intended to help with just that part of the method.
- In errors 2 and 3, it notes that the `window` is an optional and you will need to unwrap it. You can either put a `?` after the `window` variable or else make a new variable that isn't optional and set `self.window = {new variable}`.

We will update our docs - thanks!

**Comment by hokstuff** [comment]
For the first bullet, the line you'll need to add is `import braze_react_native_sdk`. Let me know if you still have issues - thanks!

**Comment by hokstuff** [comment]
Which version of the Braze React Native SDK are you using? There were [some changes](https://github.com/braze-inc/braze-react-native-sdk/blob/master/CHANGELOG.md) that were released recently which may be relevant. Also, does your IDE's IntelliSense display any suggestions around importing the Braze SDK?

**Comment by hokstuff** [comment]
It looks like it isn't able to find the ObjC Braze bridge files in your Swift code. Can you [create a bridging header](https://developer.apple.com/documentation/swift/importing-objective-c-into-swift) which allows you to import ObjC headers into your Swift project? Then, in the bridging header, you can import [BrazeReactBridge.h](https://github.com/braze-inc/braze-react-native-sdk/blob/master/iOS/BrazeReactBridge/BrazeReactBridge/BrazeReactBridge.h).

^ If this works then I will make a request to update the docs for Swift projects

**Comment by hokstuff** [comment]
Hi @bernardorubin,

Can you try a couple more changes to attempt to resolve the issue:
1. The `BrazeReactBridge` conforms to [the protocol RCTBridgeDelegate](https://github.com/braze-inc/braze-react-native-sdk/blob/0fc74254b448d3d8ef10d37fbcd877a6b55909e4/iOS/BrazeReactBridge/BrazeReactBridge/BrazeReactBridge.h#L7) so can you try removing `as? RCTBridgeDelegate`?
2. For the issue on the bottom, in our Expo plugin we implemented [this workaround](https://github.com/braze-inc/braze-expo-plugin/blob/686119b31eb1d45c9c6e79228ae7d103bb7d71d3/plugin/ios/ExpoAdapterBraze/BrazeAppDelegate.swift#L70) to address the typing discrepancy. Do you mind trying it in your project?

Thanks for your patience and help in working out this issue. We have added an item to our internal roadmap to create a Swift sample project that we can use to test integrations with our React Native SDK.

**Comment by hokstuff** [comment]
Great to hear you got it up and running! We'll update our public docs with the relevant code.

One thing to note above is that you have the following two lines copied twice:
```
    window?.rootViewController = rootViewController
    window?.makeKeyAndVisible()
```

**Comment by hokstuff** [comment]
Hi, can you contact support@braze.com with more context around your setup including:
1. What version of Xcode are you using?
2. Do you have `Enable bitcode` set to true in your project?
3. Can you attach your `podfile.lock` and your `Podfile`?
4. When you say `It only fails on App Center building`, are you referencing that this fails to upload to Apple's App Store?
5. Does this error only occur when using `BrazeUI`, or does it occur when using `BrazeKit` by itself?

**Comment by hokstuff** [comment]
Hi @bernardorubin,

The integration code will be the Swift equivalent of [this snippet in our example](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/ios/BrazeProject/AppDelegate.mm#L27).

Can you check and see if this is the sufficient translation into your Swift app? We currently have a pull request in our public docs to update to the snippet below and would appreciate if you could validate this:
```
    // Setup Braze bridge
    let jsCodeLocation : URL = RCTBundleURLProvider.sharedSettings().jsBundleURL(
      forBundleRoot: "index"
    )
    let rootView = RCTRootView(
      bundleURL: jsCodeLocation,
      moduleName: "<YOUR_PROJECT_NAME>",
      initialProperties: nil,
      launchOptions: launchOptions
    )
    self.bridge = rootView.bridge

    /* The rest of the code */
```

**Comment by davidbielik** [comment]
Hi @bernardorubin can you please raise a support ticket (you can email these details and verbose logs to support@braze.com)?

It'll be easier/faster to troubleshoot than in github which is better suited for specific SDK method bugs/feature requests.
