### ISSUE TITLE
[Bug]: Plugin with id 'kotlin-android' not found error for RN version 0.71.3

### ISSUE THREAD

**Issue by uyend** [braze-inc/braze-react-native-sdk#194]
### Which Platforms?

Android

### Which React Native Version?

0.71.3

### Which @braze/react-native-sdk SDK version?

2.0.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Try building out the android app

### Expected Behavior

App to be built successfully 

### Actual Incorrect Behavior

App unable to build due to this error: 

* What went wrong:
A problem occurred evaluating project ':braze_react-native-sdk'.
> Plugin with id 'kotlin-android' not found.

**Comment by bryanlogan** [comment]
Can you add ` classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"` on your android/build.gradle and see if that fixes the issue?

**Comment by radixdev** [comment]
Hi @uyend ,

Please take a look at our sample app (https://github.com/braze-inc/braze-react-native-sdk/blob/0fc74254b448d3d8ef10d37fbcd877a6b55909e4/android/build.gradle#L33) to see where to add the kotlin classpath addition @bryanlogan pointed out above. We've also updated our documentation (which should be live soon) to point out where to add this code to your `build.gradle` as well.

**Comment by uyend** [comment]
Thank you that helped!
