### ISSUE TITLE
[Bug]: Proper error handling and information access in content cards

### ISSUE THREAD

**Issue by Minishlink** [braze-inc/braze-react-native-sdk#198]
### Which Platforms?

Both

### Which React Native Version?

0.70

### Which @braze/react-native-sdk SDK version?

2.0.0 - 3.0.0

### Repro Rate

100%

### Steps To Reproduce

There is no way to be notified of errors. Promises don't throw.

For example, Braze.requestContentCardsRefresh is not even a promise. 

### Expected Behavior

requestContentCardsRefresh, getContentCards, logContentCardImpression etc should be promises that throw when there is an error. They should resolve once the corresponding action is done.

### Actual Incorrect Behavior

It fails silently. JS side has no idea what is going on. The only listener we have is CONTENT_CARDS_UPDATED which doesn't even send the cards as payload, it hides all the data we could have from the SDK for some reason. And it is subject to a race condition if you use getContentCards (because of contentCardsUpdatedAt). Also, as of now, I don't receive any content cards anymore 🤦‍♂️

I realize I'm talking about several issues, but honestly I'm tired of this feature which clearly has not been thought through when integrated into this bridge. Test the bridge with a full real world application before pushing into production, because really I'm starting to be afraid of having my user data on your servers if you handle your server like you handle this bridge.

**Comment by radixdev** [comment]
Hi @Minishlink ,

The native android/iOS SDKs, as of the latest Braze React SDK version, will automatically handle retries for any Content Card sync requests that experience errors. After that retry logic is successful, the subscription listeners will be called automatically once the Content Card data has been successfully retrieved. In addition to this, for the Android SDK specifically, the refresh request and client subscription flows are isolated to keep all calls asynchronous so there's not a straightforward way to attribute an error back to the originating call. 

We will look into "which doesn't even send the cards as payload" and update you if we have any API updates on that front.

Thanks,
Julian

**Comment by hokstuff** [comment]
Hi @Minishlink,

We have released [SDK version 4.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/4.0.0) which introduces a `Braze.ContentCardsUpdatedEvent` that contains the array of Content Cards as one of the fields.

Thanks!
