### ISSUE TITLE
[Bug]: card properties malformated

### ISSUE THREAD

**Issue by Minishlink** [braze-inc/braze-react-native-sdk#201]
### Which Platforms?

iOS

### Which React Native Version?

0.70

### Which @braze/react-native-sdk SDK version?

3.0.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  2. Run the app.

### Expected Behavior

getContentsCards should return an array with the form Braze.ContentCard[]

### Actual Incorrect Behavior

On iOS, it returns an array of objects in which keys are compressed. This is because `[card json]` returns such structure here https://github.com/braze-inc/braze-react-native-sdk/commit/98b3df82bdbef7db17f23ab3965bdf41096e776c#diff-bd9d7ad6d9b34132642bf2aa09c73ad5f08bb79ed6d87f0a8676491e199eff07R529
The old way was the right way (eg. a formatter), because the json structure is not strongly typed

**Comment by hokstuff** [comment]
Hi @Minishlink,

We have release [SDK version 4.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/4.0.0) which fixes this issue. Thanks!
