### ISSUE TITLE
[Bug]: Typo in PushNotificationEvent

### ISSUE THREAD

**Issue by diego-paired** [braze-inc/braze-react-native-sdk#202]
### Which Platforms?

Both

### Which React Native Version?

0.71

### Which @braze/react-native-sdk SDK version?

4.0.0

### Repro Rate

100%

### Steps To Reproduce

There appears to be a typo in `PushNotificationEvent` with the field `context_text`
Looking at the code, I believe it should be called `content_text` instead in BrazeReactBridge.kt

### Expected Behavior

content_text

### Actual Incorrect Behavior

context_text

### Additional Information

Should this field exist on iOS?

**Comment by radixdev** [comment]
Hi @diego-paired ,

That is indeed a bug and we will update you once it's fixed. Thanks for filing!

**Comment by hokstuff** [comment]
Hi @diego-paired,

We have just released [React Native version 4.1.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/4.1.0) which fixes this issue. Thanks for raising it!
