### ISSUE TITLE
[Bug]: logContentCardClicked is not working

### ISSUE THREAD

**Issue by Pholish** [braze-inc/braze-react-native-sdk#203]
### Which Platforms?

iOS

### Which React Native Version?

0.68.4

### Which @braze/react-native-sdk SDK version?

~4.0.0

### Repro Rate

100%

### Steps To Reproduce

  1. Create Content Card
  2. Add recipients  
  3. `import Braze from "@braze/react-native-sdk"`.
  4. `Braze.changeUser(id)`
  5. `Braze.setEmail(email)`
  6. `Braze.addListener(Braze.Events.CONTENT_CARDS_UPDATED, cb)`
  7. `Braze.requestContentCardsRefresh()`
  8. `Braze.logContentCardClicked(contentCardId)`
  9. Open Braze Dashboard
  10. Open Content Card Details
  11. Run the app.
  12. Check Unique Clicks and Total Clicks
  

### Expected Behavior

Unique Clicks and Total Clicks should be changed - not equal 0

### Actual Incorrect Behavior

Nothing happened - equal zero

**Comment by hokstuff** [comment]
Hi @Pholish,

We are unable to reproduce this issue in our sample app. Can you contact our Support team with more info and link this issue? Please provide verbose logs, the campaigns with issues, and any other relevant context. Also, note that if a Content Card has no click action associated with it, a Content Card click may not be sent.

Thanks!

**Comment by Pholish** [comment]
> Hi @Pholish,
> 
> We are unable to reproduce this issue in our sample app. Can you contact our Support team with more info and link this issue? Please provide verbose logs, the campaigns with issues, and any other relevant context. Also, note that if a Content Card has no click action associated with it, a Content Card click may not be sent.
> 
> Thanks!

Found! Misconfiguration in On Click Behaviour... Thanks
