### ISSUE TITLE
[Bug]: Plugin with id 'kotlin-android' not found

### ISSUE THREAD

**Issue by tusharsarkar** [braze-inc/braze-react-native-sdk#204]
### Which Platforms?

Android

### Which React Native Version?

0.71.6

### Which @braze/react-native-sdk SDK version?

4.1.0

### Repro Rate

100% of the time

### Steps To Reproduce

Example:
  1. `Add @braze/react-native-sdk and do all the setups setups for Android and iOS`.
  2. Run command `npx react-native run-android`

### Expected Behavior

App should build successfully and app should run

### Actual Incorrect Behavior

* Where:
Build file '../node_modules/@braze/react-native-sdk/android/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':braze_react-native-sdk'.
> Plugin with id 'kotlin-android' not found.

**Comment by aganov** [comment]
@tusharsarkar  you can edit `android/build.gradle` to match specs below

```gradle
buildscript {
    ext {
       // ...
       kotlinVersion = "1.7.22"
        // ...
    }
    dependencies {
        // ...
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        // ...
    }
}
```

**Comment by radixdev** [comment]
Yes, please see https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#step-2-complete-native-setup for Kotlin setup.
