### ISSUE TITLE
[Bug]: Clicking on push notifications does not open the app

### ISSUE THREAD

**Issue by aganov** [braze-inc/braze-react-native-sdk#205]
### Which Platforms?

Android

### Which React Native Version?

0.71.6

### Which @braze/react-native-sdk SDK version?

4.1.0

### Repro Rate

100%

### Steps To Reproduce

Clicking on push notifications does not open the app.

I have defined a service in the AndroidManifest.xml file and set up everything that is needed for FCM integration. The app is receiving push notifications and in-app messages, but when I click on the push notification, nothing happens.

```
      <service
        android:name="com.braze.push.BrazeFirebaseMessagingService"
        android:exported="true">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
 ```
 
I have also tried implementing a custom `FirebaseMessagingService` that handles Braze notifications through `handleBrazeRemoteMessage`, but it did not help.

### Expected Behavior

Open app on click.

### Actual Incorrect Behavior

Application is not opened.

**Comment by radixdev** [comment]
1. Please post the contents of your `braze.xml` file.
2. Please attach verbose logs of your app run.
3. You likely need to enable https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-4-add-deep-links `com_braze_handle_push_deep_links_automatically`.

**Comment by aganov** [comment]
Setting `com_braze_handle_push_deep_links_automatically` fixed the issue. Thanks.
