### ISSUE TITLE
[Bug]: logCustomEvent not allowed object has "type" key and null value

### ISSUE THREAD

**Issue by jaranda-w** [braze-inc/braze-react-native-sdk#213]
### Which Platforms?

iOS

### Which React Native Version?

0.70.5

### Which @braze/react-native-sdk SDK version?

4.0.0

### Repro Rate

100%

### Steps To Reproduce

logCustomEvent not allowed object has "type" key and null value { type: null }

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.logCustomEvent('LOG_CUSTOM_EVENT_TEST', { key: { type: null } })`
  2. Run the app.

### Expected Behavior

Success for custom logging

### Actual Incorrect Behavior

Application crashed

Exception '-[NSNull isEqualToString:]: unrecoginized selector sent to instance'

**Comment by jerielng** [comment]
Hi @jaranda-w, we've just released version [5.1.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/5.1.0) of the React Native SDK, which should resolve this issue with dictionary keys using the name `"type"`.

Please let us know if you have any further questions. Thank you!
