### ISSUE TITLE
[Bug]: Apps doesn't receive push notifications when background or killed.

### ISSUE THREAD

**Issue by plambir93kek** [braze-inc/braze-react-native-sdk#214]
### Which Platforms?

Both

### Which React Native Version?

0.71.8

### Which @braze/react-native-sdk SDK version?

^4.1.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  3. Braze.setPushNotificationSubscriptionType('subscribed');
  4. Run the app.

### Expected Behavior

When app is background or killed - push notifications should arrived and be visible.

### Actual Incorrect Behavior

When app is background or killed there are no push notifications arrived. When app is in foreground - all pushes are arrived and displayed. Using Expo managed workflow.

"@braze/expo-plugin": "^1.1.1",
 "@braze/react-native-sdk": "^4.1.0", 
"react-native": "0.71.8",
"expo-notifications": "~0.18.1"
"expo": "~48.0.15"

### Verbose Logs

```shell
No logs
```

**Comment by radixdev** [comment]
Hi @plambir93kek ,

For Android,
1. What device/OS version are you running during your tests?
2. Can you provide system level verbose logcat when receiving a push in the backgrounded and killed state? This is probably an OS level limitation if notifications are arriving while the app is in the foreground.
3. How are you backgrounding the app? How are you killing the app?

Please let us know the answers to the questions above so we can investigate.

**Comment by plambir93kek** [comment]
Hi @radixdev 
1) My team have many devices and it doesn't work with every device. For example we have Samsung Galaxy A9 and Iphone X as our test devices.
2) I will add logs here at Monday. Seems like it is not OS issue, because non of our testers with different devices receive pushes.
3) I mean "killed" when app is not launched.  App in background: "On most, if not all, smart phones available you can have multiple apps running at once. When you have an app running, but it’s not the focus on the screen it is considered to be running in the background."

**Comment by plambir93kek** [comment]
@radixdev Logs form Android:


Background:

06-14 16:36:53.634   583   667 D ActivityManager: freezing 6018 com.google.android.configupdater
06-14 16:36:53.637   583   667 W ActivityManager: Unable to freeze 6018 com.google.android.configupdater
06-14 16:36:53.637   583   667 D ActivityManager: freezing 1582 com.google.process.gservices
06-14 16:36:53.638   583   667 W ActivityManager: Unable to freeze 1582 com.google.process.gservices
06-14 16:36:54.200   583   667 D ActivityManager: freezing 6017 com.google.android.apps.photos
06-14 16:36:54.201   583   667 W ActivityManager: Unable to freeze 6017 com.google.android.apps.photos


Killed:

06-14 16:39:29.063   583  1122 I ActivityManager: Killing 2467:com.google.android.apps.maps/u0a117 (adj 955): empty for 1810s
06-14 16:39:29.069   583  1122 I ActivityManager: Killing 4345:com.google.android.gms.ui/u0a100 (adj 955): empty for 1814s
06-14 16:39:29.073   583  1122 I ActivityManager: Killing 4571:com.android.remoteprovisioner/u0a131 (adj 965): empty for 1819s
06-14 16:39:29.073   583  1122 I ActivityManager: Killing 2379:android.process.media/u0a59 (adj 965): empty for 1818s
06-14 16:39:29.081   583   613 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10172; state: DISABLED
06-14 16:39:29.081   583   613 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10172; state: DISABLED
06-14 16:39:29.081   583   613 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10172; state: DISABLED
06-14 16:39:29.081   583   613 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10172; state: ENABLED
06-14 16:39:29.082   583   614 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10172; state: ENABLED
06-14 16:39:29.111   583   614 I ActivityManager: Start proc 6469:com.ronasit.thetenn.dev/u0a172 for broadcast {com.<OUR_APP_PACKAGE_NAME>/com.google.firebase.iid.FirebaseInstanceIdReceiver}
06-14 16:39:45.840   583   619 D KernelCpuUidUserSysTimeReader: Removing uids 99002-99002

**Comment by radixdev** [comment]
Hello @plambir93kek ,

We have a fix developed and will update this issue once it's released.

**Comment by hokstuff** [comment]
Hi @plambir93kek,

This issue has been fixed in [React Native SDK 5.2.0](https://github.com/braze-inc/react-native-sdk/blob/develop/public/CHANGELOG.md#520). Thanks!
