### ISSUE TITLE
[Bug]: Issue with BrazeReactBridge.kt when migrate from appboy to @braze/react-native-sdk android

### ISSUE THREAD

**Issue by juliaitbaeva** [braze-inc/braze-react-native-sdk#217]
### Which Platforms?

Android

### Which React Native Version?

0.64.0

### Which @braze/react-native-sdk SDK version?

2.0.0

### Repro Rate

100% of time

### Steps To Reproduce

1. Install npm package @braze/react-native-sdk": "^2.0.0"
2. Do all instructions Initial SDK setup for android. https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/#prerequisites-and-compatibility
3. Run android simulator from Android Studio, build failed
4. Build failed with error 
```
> Task :braze_react-native-sdk:compileDebugKotlin
e: /Users/iuliia/project/node_modules/@braze/react-native-sdk/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt: (409, 52): Unresolved reference: hasActiveReactInstance
e: /Users/iuliia/project/node_modules/@braze/react-native-sdk/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt: (429, 52): Unresolved reference: hasActiveReactInstance
e: /Users/iuliia/project/node_modules/@braze/react-native-sdk/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt: (448, 42): Unresolved reference: hasActiveReactInstance
e: /Users/iuliia/project/node_modules/@braze/react-native-sdk/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt: (471, 42): Unresolved reference: hasActiveReactInstance

> Task :braze_react-native-sdk:compileDebugKotlin FAILED
```

### Expected Behavior

Expected that build would be successful, without errors

### Actual Incorrect Behavior

Build failed with error in kotlin module BrazeReactBridge

**Comment by bryanlogan** [comment]
The Braze React Native SDK v2.0.0 itself has a requirement of React Native v.0.68+.  https://github.com/braze-inc/react-native-sdk/blob/develop/public/CHANGELOG.md#200

Are you able to upgrade your RN version?

**Comment by juliaitbaeva** [comment]
![Screenshot 2023-06-05 at 12 37 18 PM](https://github.com/braze-inc/braze-react-native-sdk/assets/100954386/3dff1c6a-9b1e-404a-a2df-264613b6f30a)
I can try to update to RN 0.68
In case If it doesn't help I can downgrade to Braze React Native SDK  1.38.0. If I'm not wrong 1.38.0. version is it appboy sdk?

**Comment by bryanlogan** [comment]
Being the "appboy sdk" doesn't matter, they both point to the same servers.  If you can't upgrade to RN 0.68, I would try to use Braze React Native 1.41.0 (the final version before 2.0.0).
