### ISSUE TITLE
How not to request push permission upon launching the app using Expo?

### ISSUE THREAD

**Issue by plambir93kek** [braze-inc/braze-react-native-sdk#218]
### Which Platforms?

Both

### Which React Native Version?

0.71.8

### Which @braze/react-native-sdk SDK version?

^4.1.0

### Repro Rate

100%

### Steps To Reproduce

1) Set up Braze for React Native Expo.
2) First time after installation launch the app.

The first time the app is launched, Braze immediately requests push notifications permission. How to avoid this and control permission's request?

### Expected Behavior

Notification permission and token should be asked only when i call `Braze.requestPushPermission(permissionOptions);`

### Actual Incorrect Behavior

The first time the app is launched, Braze immediately requests push notifications permission and i can't prevent it.

**Comment by plambir93kek** [comment]
Please note, i am using Expo managed workflow.

**Comment by plambir93kek** [comment]
That was my mistake. Problem was related to other SDK my app using, not Braze.

**Comment by ioetbc** [comment]
Hey @plambir93kek i'm having the same problem, are you able to expand your answer? which SDK was causing the actual issue?

**Comment by ioetbc** [comment]
thank for getting back so quick @jerielng here is my configuration:
`[
        "@braze/expo-plugin",
        {
          iosApiKey: process.env.BRAZE_IOS_API_KEY,
          androidApiKey: process.env.BRAZE_ANDROID_API_KEY,
          baseUrl: process.env.BRAZE_BASE_URL,
          firebaseCloudMessagingSenderId:
            process.env.FIREBASE_CLOUD_MESSAGING_SENDER_ID,
          enableBrazeIosPush: true,
          iosRequestPushPermissionsAutomatically: false,
          enableFirebaseCloudMessaging: true,
        },
      ],`
      
     I'm only experiencing this on IOS. 
     
     Thanks!

**Comment by jerielng** [comment]
@ioetbc Thanks for the details! It looks like you should have it configured correctly. That `iosRequestPushPermissionsAutomatically` setting should disable this feature. Unfortunately, I'm not able to reproduce this from our end. Our best recommendation is to verify that the authorization request is not coming from a separate SDK or configuration, as **plambir93kek** experienced.

If you are still facing this issue even after ruling out any other SDKs, could you write into our support team at support@braze.com with as many details as you can provide about your project setup (SDK versions, any relevant integration code), and if possible provide a minimal reproducible sample?
