### ISSUE TITLE
[Bug]: invalid api key error and changeUser not working

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [braze-inc/braze-react-native-sdk#219]
### Which Platforms?

iOS

### Which React Native Version?

0.71.4

### Which @braze/react-native-sdk SDK version?

5.0.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  2. Run the app.

### Expected Behavior

no error about braze when i init my app and i can see the test user's profile on the braze dashboard

### Actual Incorrect Behavior

invalid api key error happened
[braze] Platform api error.
- reason: invalid_api_key

i changed user but dash can't find the user
[native] braze changeUser with values some-user-id2 (null)
[braze] Changed user to 'some-user-id2'.
<img width="492" alt="스크린샷 2023-06-11 오후 4 36 58" src="https://github.com/braze-inc/braze-react-native-sdk/assets/79429899/661b3118-3b8b-420e-9f67-9630b5d29e66">

### Additional Information

i put the api key that is in the braze setting page, and it is 100% correct

and, i also edited my AppDelegate.mm watching the braze-react-native-sdk's code

what should i do??

**Comment by jerielng** [comment]
Hi @taehyun-kim-tenuto, could you confirm if this is happening on iOS only and not on Android as well, or is this happening on both platforms? One thing to note is that the API key you got from the dashboard settings should be different between your iOS app and your Android app. When selecting your app in the dashboard, you should be able to see that it's an API key specific to Apple, like this:

![image](https://github.com/braze-inc/braze-react-native-sdk/assets/16450008/3611d8bc-f655-4480-bcea-fcde5a5856ec)

Beyond that, is there anything else you can share about how you are initializing the Braze configuration? Can you confirm that the sample code you were referencing is based on this [AppDelegate](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/ios/BrazeProject/AppDelegate.mm#L40-L44) here?

**Comment by taehyun-kim-tenuto** [comment]
it only happens on iOS
i exactly selected iOS API Key and put it in my AppDelegate
and yes, i wrote AppDelegate referencing that code as well

**Comment by taehyun-kim-tenuto** [comment]
plus i also got this error
APNS device token not set before retrieving FCM Token for Sender ID '??????????'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

**Comment by taehyun-kim-tenuto** [comment]
my bad, my api key was wrong sorry i will close this issue
