### ISSUE TITLE
[Feature]: Set Channel priority for android

### ISSUE THREAD

**Issue by TylerJackson** [braze-inc/braze-react-native-sdk#225]
### What problem are you facing?

Our push notifications need to be urgent as the related content we want them to know about is time sensitive. There is no way to set the urgency level for the message sent or a channel. Specifically I am talking about android where we want the messages to display a banner overlaying their current activity for the user regardless of what the user is doing.

### Workarounds

No workarounds

### Ideal Solution

In the braze xml file where we specify the channel name (is this even needed?) we can specify the urgency we want associated with the channel.

    <string name="com_braze_default_notification_channel_name">App</string>
    <string name="com_braze_default_notification_channel_urgency">HIGH</string>

### Other Information

There is a lot of configuration between the example project and the docs that seem to be different or unmentioned. For example, in the channel configuration from the braze dashboard we have a channel name and also a channel id. What is this tag in the braze.xml file? Where is the documentation on it?

**Comment by radixdev** [comment]
Hi @TylerJackson ,

Please see [this docs page](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-5-define-notification-channels) for a good overview of the following. 

On Android, push notifications are sent to "Notification Channels" that are app-created but user-maintained. Meaning that the initial importance and display properties for a Notification Channel can be overridden by the user at any time post creation. That braze.xml configuration is referring to the Notification Channel created in the event that the Notification Channel set on the dashboard by you either wasn't supplied or doesn't exist. If you would like to have a Notification Channel with a high importance, we would recommend that you create that channel in native code and specify the Notification Channel ID on the dashboard for Braze to use. However note that the end user can change that importance (or silence them entirely) at their discretion. You may also use FCM priority https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings/#fcm-priority to ensure that push makes it to the end user's device at the highest possible Firebase priority as well.

**Comment by TylerJackson** [comment]
@radixdev The fact that I need to implement it on my own via native code is why it would be a good feature to add to the react native sdk. For a react native sdk I shouldn't have to edit anything in native code beyond unavoidable OS specific setup (ideally).
