### ISSUE TITLE
[Bug]: Double Activity shows up on Android in Recents tasks when a Push Notification is Clicked

### ISSUE THREAD

**Issue by vivekm-remitly** [braze-inc/braze-react-native-sdk#231]
### Which Platforms?

Android

### Which React Native Version?

0.70.8

### Which @braze/react-native-sdk SDK version?

7.0.0

### Repro Rate

100% on Android 14

### Steps To Reproduce

The repro steps are similar to what was reported in this Android SDK issue. 

https://github.com/braze-inc/braze-android-sdk/issues/12

### Expected Behavior

On Android 14, the behavior should be consistent with previous Android versions ie. it should be same as Android 13.

### Actual Incorrect Behavior

The behavior is different from Android 13. When the same steps are followed on Android 13, only a single task shows in the Recent tasks drawer. Attached video for Android 13 in the original issue thread. 

https://github.com/braze-inc/braze-android-sdk/issues/12

### Additional Information

The issue was originally reported in the [braze-android-sdk](https://github.com/braze-inc/braze-android-sdk/issues/12) repo. Today Android SDK's `v29.0.0` was released to fix the issue. The React Native SDK is currently using `v27.x`. RN SDK should be bumped to start using the latest Android SDK that contains the fix. 

Since, Android 14 was officially released today (Oct 4th, 2023), we would appreciate a fix for it to be made as early as possible.

**Comment by jerielng** [comment]
Hi @vivekm-remitly, thanks for your patience. We have an upcoming release in the works that will bump the Android SDK version to `29.0.0`. While we don't have an exact timeline for this, we will keep you updated as soon as this is out.

Thank you!

**Comment by vivekm-remitly** [comment]
Closing this as SDK `8.0.0` uses Android SDK version `29.0.0`
