### ISSUE TITLE
Trigger Content Card Default Feed only when we send a Content Card from Braze

### ISSUE THREAD

**Issue by msaaddevkyte** [braze-inc/braze-react-native-sdk#232]
### Which Platforms?

Both

### Which React Native Version?

0.71.11

### Which @braze/react-native-sdk SDK version?

^6.0.1

### Repro Rate

100% of the time

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. Put `Braze.changeUser("id")` in `useEffect`
  3. Put `Braze.launchContentCards();` in the same useEffect after step 2.

### Expected Behavior

I don't want to open the Content Card feed when the user clicks on something. It should automatically open up when we send a Content card. That's why, I added it to the `useEffect`. 

### Actual Incorrect Behavior

The empty feed is opening up every other second.

### Additional Information

https://github.com/braze-inc/braze-react-native-sdk/assets/139242622/e70cda0a-fd10-4f92-a166-b6c509a3a0b8

**Comment by msaaddevkyte** [comment]
I read the docs again and added the following code:

```
Braze.addListener(Braze.Events.CONTENT_CARDS_UPDATED, async (update) => {
  if (update.cards.length) {
    Braze.launchContentCards();
  }
});

Braze.requestContentCardsRefresh();
```

Right now, I am not seeing any empty feed but I am not sure if it works. I tested it but when I sent the content card from Braze, the array was still empty. It could be due to other reasons but I have a question about whether the above code only works for the Custom Content Card feed. Or will it work for the default feed as well?

**Comment by msaaddevkyte** [comment]
Hi @jerielng!

Thanks for the explanation. Yes, we have already implemented the In-App Messages. About the Content Cards, the following worked for me:

```
const contentCardsSubscription = Braze.addListener(
  Braze.Events.CONTENT_CARDS_UPDATED,
  async (update) => {
    if (update.cards.length) {
      Braze.launchContentCards();
    }
  },
);

return () => {
  if (contentCardsSubscription) {
    contentCardsSubscription.remove();
  }
};
```

Now the CC feed opens up whenever there is a Content Card. I was using ` Braze.requestContentCardsRefresh();` earlier which led to the feed opening every other second if a Content Card exists. What do you think about the above implementation? Do you see any downside to it?

One thing I noticed was in the feed, there were previous CCs as well as the new one I am sending from Braze. Is this normal? Do we delete the previously sent cards from Braze?

**Comment by jerielng** [comment]
> What do you think about the above implementation? Do you see any downside to it?

It should work as intended if that is the desired behavior. However, that listener will trigger any time there is an update to the user's CCs, so depending on how often that happens, it might get disruptive to the user's experience. I would recommend to test it heavily to see if that is ideal for your use case.

> One thing I noticed was in the feed, there were previous CCs as well as the new one I am sending from Braze. Is this normal? Do we delete the previously sent cards from Braze?

Yes, that's expected. CCs are supposed to persist for the user until they're either removed by the user or the user is no longer eligible to receive that campaign for whatever reason. Think something similar to your notifications feed in a given app. For more details on the use cases, you can also look at our code-agnostic docs [here](https://www.braze.com/docs/user_guide/message_building_by_channel/content_cards).

**Comment by msaaddevkyte** [comment]
@jerielng can you please explain when you say "there is an update to the user's CCs"? Does Braze has a list somewhere where the cards are listed that can be updated?

**Comment by jerielng** [comment]
> there is an update to the user's CCs

This simply means whenever you refresh your list of CCs. These are the cards that persist for the user until they expire and are the same cards that appear on that feed UI. For example, you can access the list of CCs for a given user with these [methods](https://github.com/braze-inc/braze-react-native-sdk/blob/master/src/index.d.ts#L499-L509).

**Comment by jerielng** [comment]
Hi @msaaddevkyte, we'll be closing out this issue due to inactivity, but feel free to re-open it if you have any further questions or are still facing issues with implementing Content Cards. Thanks!
