### ISSUE TITLE
[Bug]: Push Notifications Deep Links not working when application in background thread 

### ISSUE THREAD

**Issue by admirsaheta** [braze-inc/braze-react-native-sdk#235]
### Which Platforms?

iOS

### Which React Native Version?

0.70.1

### Which @braze/react-native-sdk SDK version?

8.0.0

### Repro Rate

100%

### Steps To Reproduce

```
  setupLinking = async () => {
    // Listen to links opened when the app is closed
    const initialLink = await Linking.getInitialURL();

    if (initialLink) {
      this.onURLEvent({ url: initialLink });
    }

    // Listen to links opened in the app or when the app is in background
    Linking.addEventListener('url', this.onURLEvent);
  };

```

And the ObjC++ methods are

```
#pragma mark - Linking

// Deep Linking
// For deep links
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
// For universal links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

### Expected Behavior

For App to open Deeplink even in background thread on iOS

### Actual Incorrect Behavior

Application just opens to default screen

**Comment by jerielng** [comment]
Hey @admirsaheta, we have a support method [here](https://github.com/braze-inc/braze-react-native-sdk/blob/master/src/index.d.ts#L6-L14) that allows you to process deep links on iOS when the app isn't actively running. The comment explains a bit about the limitations in the React Native `Linking` function. This should allow you to open deeplinks from a background thread.

If you'd like further details on how to use this in conjunction with the default `Linking.getInitialURL`, you can refer to our sample app [here](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/BrazeProject.tsx#L152-L176).
