### ISSUE TITLE
[Bug]: Redefinition of 'NativeBrazeReactModuleSpecJSI' on new arch

### ISSUE THREAD

**Issue by huextrat** [braze-inc/braze-react-native-sdk#243]
### Which Platforms?

iOS

### Which React Native Version?

0.73.2

### Which @braze/react-native-sdk SDK version?

8.3.0

### Repro Rate

100%

### Steps To Reproduce

  1. `import Braze from "@braze/react-native-sdk"`.
  2. Build iOS app with the new arch enabled

### Expected Behavior

Should build the app

### Actual Incorrect Behavior

Building the app on iOS give the following error `Redefinition of 'NativeBrazeReactModuleSpecJSI'` on the following line `class JSI_EXPORT NativeBrazeReactModuleSpecJSI : public ObjCTurboModule {` 

The error seems to come from https://github.com/braze-inc/braze-react-native-sdk/blob/7967b9a19d8dec1257c12d6776f866d647912aa6/iOS/BrazeReactBridge/BrazeReactBridge/BrazeReactBridge.mm#L1079C9-L1079C9

**Comment by jerielng** [comment]
Hi @huextrat, we aren't able to reproduce this from our end. Are you able to reproduce the same issue in our sample app [here](https://github.com/braze-inc/braze-react-native-sdk/tree/master/BrazeProject) or in a fresh React Native project?

Could you also verify if the issue persists after clearing out any caches and derived data as well as re-installing your CocoaPods?

It might help to get some insight into how your project environment is configured. Could you send in the following information to support@braze.com to work with our support team to diagnose this issue:
* AppDelegate file
* Podfile
* Xcode version
* Any other relevant dependencies in your `package.json`

**Comment by huextrat** [comment]
Thx @jerielng it's working well on sample app. Also getting the error on my project for Android `Redeclaration: BrazeReactBridge`.

I will investigate it seems to be a conflict between folders `newarch` & `oldarch` who contains same file name, but it's the correct way to make a lib compatible with both arch.
