### ISSUE TITLE
[Bug]: Jest issue

### ISSUE THREAD

**Issue by atrofimenko** [braze-inc/braze-react-native-sdk#244]
### Which Platforms?

Both

### Which React Native Version?

0.70.5

### Which @braze/react-native-sdk SDK version?

8.2.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. Run jest tests update

### Expected Behavior

No errors

### Actual Incorrect Behavior

Getting this error when trying to run tests
![Screenshot 2024-02-06 at 18 02 37](https://github.com/braze-inc/braze-react-native-sdk/assets/62396722/1d794a78-7d32-4f5b-8869-bd0fd5a4b14f)
After some manipulations with jest config, like:
"transformIgnorePatterns": [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@rneui/.*|@gorhom/.*|@braze/react-native-sdk)"
  ],
 Getting this error:
![Screenshot 2024-02-06 at 17 58 40](https://github.com/braze-inc/braze-react-native-sdk/assets/62396722/d2e626cf-93f3-4af0-8c56-86b75c19d15f)
Any thoughts how to fix this?) Thank you.

**Comment by jerielng** [comment]
Hey @atrofimenko, are you upgrading from a previous version of the Braze SDK? We made some internal changes in version [6.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/6.0.0) to support the React Native New Architecture. It looks like you may need to update how you import the Braze module. You can refer to our sample test setup [here](https://github.com/braze-inc/braze-react-native-sdk/tree/master/__tests__).

**Comment by atrofimenko** [comment]
> Hey @atrofimenko, are you upgrading from a previous version of the Braze SDK? We made some internal changes in version [6.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/6.0.0) to support the React Native New Architecture. It looks like you may need to update how you import the Braze module. You can refer to our sample test setup [here](https://github.com/braze-inc/braze-react-native-sdk/tree/master/__tests__).

@jerielng Thank you! Copied all the content of the file __tests__/jest.setup.js to my setup and it did not help me

**Comment by atrofimenko** [comment]
> Hey @atrofimenko, are you upgrading from a previous version of the Braze SDK? We made some internal changes in version [6.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/6.0.0) to support the React Native New Architecture. It looks like you may need to update how you import the Braze module. You can refer to our sample test setup [here](https://github.com/braze-inc/braze-react-native-sdk/tree/master/__tests__).

Changed path to NativeBrazeReactModule and added back transformIgnorePatterns - now it works, thank you!
