### ISSUE TITLE
[Bug]: Could not connect to the server Braze

### ISSUE THREAD

**Issue by rajneeshraghav** [braze-inc/braze-react-native-sdk#246]
### Which Platforms?

iOS

### Which React Native Version?

0.72.4

### Which @braze/react-native-sdk SDK version?

8.0.3

### Repro Rate

100%

### Steps To Reproduce

Upgrade to React Native 0.72.4 from React Native 0.65.1, migrate to Braze SDK from Appboy SDK

### Expected Behavior

User should get notifications on devices if device token and is registered and user is registered  

### Actual Incorrect Behavior

user is not getting PN on ios

### Verbose Logs

```shell
Current user is already identified as "*********************".
- location: BrazeKit/BrazeApi+ObjC.swift:241
- function: changeUser(userId:sdkAuthSignature:fileID:line:)
- parameter: userId

The value is not supported.
- value: ""
- type: Swift.String
- location: BrazeKit/ConfigurationExt.swift:9
- function: errors
- parameter: api.endpoint

HTTP URL error:
- code: -1004
- description: "Could not connect to the server."
- url: [POST] https:///api/v3/data
- headers:
  - Content-Type: application/json
  - X-Braze-Api-Key: ***********************
  - X-Braze-DataRequest: true
  - X-Braze-FeedRequest: true
  - X-Braze-Last-Req-Ms-Ago: 2614517
  - X-Braze-Req-Attempt: 41
  - X-Braze-TriggersRequest: true
```

**Comment by jerielng** [comment]
Hi @rajneeshraghav, it looks like the SDK is not fully initialized since an empty string is being passed into the endpoint field. Could you verify that you have initialized your Braze instance according to the [setup docs](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/?subtab=objective-c&tab=ios)? Thanks!

**Comment by rajneeshraghav** [comment]
Hi @jerielng , thanks for suggestion, i added it as hardcoded, but still seeing below error - 
Task <0DC9162C-623F-43F7-B971-6C301D3342CE>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600000da9a10 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0DC9162C-623F-43F7-B971-6C301D3342CE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0DC9162C-623F-43F7-B971-6C301D3342CE>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://sdk.fra-01.braze.eu/api/v3/data, NSErrorFailingURLKey=https://sdk.fra-01.braze.eu/api/v3/data, _kCFStreamErrorDomainKey=4}

**Comment by rajneeshraghav** [comment]
thanks @jerielng , it is working
