### ISSUE TITLE
[Bug]: React Native defaulting In App Message trigger to 1s

### ISSUE THREAD

**Issue by daniel-johns-99** [braze-inc/braze-react-native-sdk#249]
### Which Platforms?

iOS

### Which React Native Version?

0.64.0

### Which @braze/react-native-sdk SDK version?

8.3.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Create a Campaign with a Event Trigger
  2. Open the app and perform the event
  3. Notice the Campaign gets executed
  4. Within 30s perform the same event
  5. Notice the Campaign gets triggered again

### Expected Behavior

As per the documenation https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery/?tab=objective-c#minimum-time-interval-between-triggers on iOS 
> By default, we rate limit in-app messages to once every 30 seconds to ensure a quality user experience.

However, for iOS this does not seem to happen. Instead the rate limit is being set at 1s

### Actual Incorrect Behavior

This is not consistent with the iOS documentation, nor the Android Experience. 
It seems as part of the React Native SDK, the value of triggerMinimumTimeInterval  is being set to 1s
#https://github.com/braze-inc/braze-react-native-sdk/blob/7967b9a19d8dec1257c12d6776f866d647912aa6/BrazeProject/ios/BrazeProject/AppDelegate.mm#L31

### Additional Information

The Behaviour of iOS and Android should be consistent. We should not override the value of triggerMinimumTimeInterval  unless there is a need to, and if so this should be documented that it is being overridden. 
The documentation refers to the iOS Swift SDK for implementation details so I do not expect this default to have been set.

**Comment by jerielng** [comment]
Hey @daniel-johns-99, are you still facing any issues with this, given the information above? If not, due to inactivity, I'll go ahead and close out this issue. Feel free to re-open it if you have other questions/concerns on this topic. Thanks!
