### ISSUE TITLE
[Bug]: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by mickeyhead7** [braze-inc/braze-react-native-sdk#251]
### Which Platforms?

iOS

### Which React Native Version?

0.72.7

### Which @braze/react-native-sdk SDK version?

9.0.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Create fresh React Native app
  2. Add "@braze/react-native-sdk" as a dependency and install pods
  3. Create a new iOS app extension target (any will do, e.g. Intents UI Extension)
  4. Attempt to build or run app via Xcode

### Expected Behavior

App should build/run without build error.

### Actual Incorrect Behavior

Build fails with error message from `KeyboardFrameNotifier.swift` (lines 25 & 32)

```
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
```

### Additional Information

According to Apple documentation, a build with app extension cannot contain dependencies that are unavailable to app extensions, or contain code incompatible with app extensions. Any such dependencies should be marked as unavailable to app extensions, e.g. using the Swift `available API`:

```
@available(iOSApplicationExtension, unavailable)
class ...
```

Some information on app extensions are available [here](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) and [here](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6).

**Comment by jerielng** [comment]
Hey @mickeyhead7, are you including BrazeUI as part of your app extension? We aren't able to reproduce this unless explicitly including it in the linked frameworks for that app extension, which isn't expected behavior. Is your use case specifically needing use Braze in your extension?

If you can provide any additional details around how you are integrating our libraries into your project, that would be a huge help. Thanks!

**Comment by mickeyhead7** [comment]
Hi @jerielng 👋 

Thanks for the quick reply. My app extension is being added to an existing app. I haven't specifically included BrazeUI in my extension, so am assuming it was inherited when the extension was created in Xcode (literally File > New > Target > Intents UI Extension.

I will have a look to see if that inheritance is the case and see if it can be removed.

**Comment by mickeyhead7** [comment]
Yeah, I believe this isn't your issue if the framework/pods can be excluded from app extensions (I'm still figuring this out).

I guess it would be more of a "nice to have" in a sense that it would remove any build errors. However this might mask that the dependency is being included for app extensions when it doesn't need to be ¯\_(ツ)_/¯
