### ISSUE TITLE
[Feature]: New architecture and bridgeless support

### ISSUE THREAD

**Issue by brentvatne** [braze-inc/braze-react-native-sdk#252]
### What problem are you facing?

Hi there! I'm working on supporting the roll out of the [new architecture + bridgeless](https://reactnative.dev/docs/the-new-architecture/landing-page) with Expo and Meta, and as part of that we identified which libraries are depended on by the largest apps or the most popular native libraries on [EAS Build](https://docs.expo.dev/build/introduction/) to help prioritize which libraries to investigate. @braze/react-native-sdk came up on that list. [See the list on Google Sheets](https://docs.google.com/spreadsheets/d/1F1tI9PQLl_uab3HNYNwgjPVL2r0hJ9VymXcgDp5etdg/) (request edit access if you'd like to update the status of @braze/react-native-sdk after testing, or if you prefer to report back here on this issue it's fine too). 

We want to start recommending folks try out the new architecture in the next release, react-native 0.74 / Expo SDK 51. Ideally we can get the ecosystem ready to switch over to the new architecture within the next few releases. So, we'll have from now until 0.74 release (before May) to give Meta feedback on anything that might not be working as expected with the new arch/bridgeless enabled.

Folks at Meta would really appreciate it if you could test your libraries against the latest release and report any issues that you find. **This new version enables an interop layer by default**, so hopefully many things will just work, but the more off of the beaten path of a simple module / view that a library goes the more likely it is to encounter possible issues ;) The following gist includes a step by step process for how to test your library and report issues: https://gist.github.com/cipolleschi/82b7a9561b8861330efabbd3eb08c6f5.

### Workarounds

None

### Ideal Solution

The library supports new architecture and bridgeless in React Native 0.74

**Comment by brentvatne** [comment]
thank you @jerielng!

**Comment by jerielng** [comment]
Closing this out with the release of Expo SDK 51 - we have been able to confirm that the Braze Expo plugin and React Native SDK are compatible with the latest versions. Thanks for the alert!

**Comment by brentvatne** [comment]
@jerielng - great, thank you!
