### ISSUE TITLE
[Bug]: NoClassDefFoundError com.braze.support.ReflectionUtils$g

### ISSUE THREAD

**Issue by mariokris** [braze-inc/braze-react-native-sdk#253]
### Which Platforms?

Android

### Which React Native Version?

0.70.3

### Which @braze/react-native-sdk SDK version?

8.1.0

### Repro Rate

100%

### Steps To Reproduce

I don't know how to reproduce this error, but this error always logged on sentry dashboard logger.

### Expected Behavior

There is no error in the sentry dashboard log about this NoClassDefFoundError : com.braze.support.ReflectionUtils$g

### Actual Incorrect Behavior

Found that error on Sentry (error logger platform), but actually, we can't reproduce it in the development stage (Android & Ios).

### Additional Information

Generally, this error happened on Android 11 below, and there is no error log in iOS, this error only happen on android platform. Specifically on Android 11, 10, 8, 7, 6.
Anybody ever facing this issue? please let me know.
Thanks.

**Comment by hokstuff** [comment]
Hi @mariokris,

Can you contact support@braze.com with more details around the logs you are seeing, as well as adding any additional verbose logs? Also, please provide any additional details if you have a particular integration method outside of simply importing the Braze React Native SDK.

Thanks!
