### ISSUE TITLE
[Bug]: malformed export/typing

### ISSUE THREAD

**Issue by suga0828** [braze-inc/braze-react-native-sdk#266]
### Which Platforms?

Both

### Which React Native Version?

0.74.1

### Which @braze/react-native-sdk SDK version?

12.1.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `Install @braze/react-native-sdk`
  2. `import * as Braze from "@braze/react-native-sdk"` (as in documentation).
  3. `Braze.changeUser("id")`
  4. Run the app.

### Expected Behavior

Typing should works.work

### Actual Incorrect Behavior

The real error is that export and typing defined inside the lib don't match (exporting default in `index.js` but individual typing in `index.d.ts`) 
![image](https://github.com/user-attachments/assets/0db09b01-4740-4022-83f5-068407fa528d)

**Comment by jerielng** [comment]
@suga0828 Sorry, could you clarify what exactly is the error you are seeing here? What behavior in the typing are you expecting to see? Is it on a specific set of methods, or just the top-level `Braze` object as a whole?

If you could provide any specific examples on what you are expecting vs. what is actually showing up in your editor, that would help us assist you better. Thanks!

**Comment by vanessaland** [comment]
Closing out this issue due to inactivity.

If you would need further assistance, feel free to reach out to our support team at [support@braze.com](mailto:support@braze.com) with the supporting information listed above.

Thank you!
