### ISSUE TITLE
[Bug]: requestContentCardsRefresh doesn't work as expected

### ISSUE THREAD

**Issue by WojciechRupik** [braze-inc/braze-react-native-sdk#267]
### Which Platforms?

iOS, Android

### Which React Native Version?

0.71.19

### Which @braze/react-native-sdk SDK version?

12.1.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  3. 
```
componentDidMount() {
    Braze.addListener(Braze.Events.CONTENT_CARDS_UPDATED, async (update) => {
      console.log('update', update)
      this.setState({ cards: update.cards })
    })

    Braze.requestContentCardsRefresh()
}
```

### Expected Behavior

User should be able to see newest card after `requestContentCardsRefresh` trigger

### Actual Incorrect Behavior

To able to see newest card i need to click on push notification

### Additional Information

[ios code](https://github.com/braze-inc/braze-react-native-sdk/blob/3.0.0/iOS/BrazeReactBridge/BrazeReactBridge/BrazeReactBridge.m#L516)

[android code](https://github.com/braze-inc/braze-react-native-sdk/blob/3.0.0/android/src/main/java/com/braze/reactbridge/BrazeReactBridge.kt#L377)

**Comment by rajneeshraghav** [comment]
Not working, any workaround ?

**Comment by jerielng** [comment]
Hey @WojciechRupik, it looks like the code snippet you shared uses a different method from the one you linked. Please write in to support@braze.com with the following details:
1. Sample code of how you are integrating Braze (specifically around Content Cards and which Content Cards methods you are calling) and where you are calling that.
2. You mentioned you have to click on the push notification. Is this a test send?
3. What steps you took in your app to reproduce this
4. Verbose logs from the Braze SDK as you reproduced this
5. Which platforms you are observing it on

and reference this GitHub issue in your email. Thank you!

**Comment by vanessaland** [comment]
Closing out this issue due to inactivity.

If you would need further assistance, feel free to reach out to our support team at [support@braze.com](mailto:support@braze.com) with the supporting information listed above.

Thank you!
