### ISSUE TITLE
[Bug]: Can't run app with Android 

### ISSUE THREAD

**Issue by vuongnguyenthanh-agilityio** [braze-inc/braze-react-native-sdk#269]
### Which Platforms?

Android

### Which React Native Version?

0.73.6

### Which @braze/react-native-sdk SDK version?

12.2.0

### Repro Rate

100% og the time

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  2. Run the app.

### Expected Behavior

Build Android app suceess

### Actual Incorrect Behavior

Build Android app failed

### Verbose Logs

```shell
Class 'com.braze.ui.inappmessage.BrazeInAppMessageManager.Companion' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.0.0, expected version is 1.8.0.
The class is loaded from /Users/vuongnguyen/.gradle/caches/transforms-3/de8802ef96b98b2a6022a08a83eace76/transformed/jetified-android-sdk-ui-33.0.0-api.jar!/com/braze/ui/inappmessage/BrazeInAppMessageManager$Companion.class
```

**Comment by radixdev** [comment]
Hi @vuongnguyenthanh-agilityio ,

1. Are you calling `implementation 'com.braze:android-sdk-ui:+'` anywhere in your build.gradle ? 
2. Can you provide your app's `build.gradle` file?

**Comment by vuongnguyenthanh-agilityio** [comment]
@radixdev Yes, you are right.
I updated to `implementation "com.braze:android-sdk-ui:31.1.0"` and it worked well. Thanks so much!
