### ISSUE TITLE
[Bug]: Build fails on React Native 0.76.0 and 0.76.1

### ISSUE THREAD

**Issue by edapess** [braze-inc/braze-react-native-sdk#273]
### Which Platforms?

iOS

### Which React Native Version?

0.76.0 / 0.76.1

### Which @braze/react-native-sdk SDK version?

13.1.1

### Repro Rate

100% of time

### Steps To Reproduce

Example:
  1. update React Native to 0.76.
  2. try to build
  3. build fails
  4. update @braze/react-native-sdk to latest  13.1.1
  5. try to build
  6. fails

### Expected Behavior

Application need to build correctly

### Actual Incorrect Behavior

Build Fails

### Verbose Logs

```shell
'optional' file not found 
while building module 'RCTTypeSafety' imported from .../ReactCodegen/ReactCodegen.framework/Headers/BrazeReactModuleSpec/BrazeReactModuleSpec.h:24:
```

### Additional Information

![Screenshot 2024-10-30 at 4 17 15 PM](https://github.com/user-attachments/assets/5768cd42-adca-4ab8-97a5-0073c1aa8253)
![Screenshot 2024-10-30 at 4 17 21 PM](https://github.com/user-attachments/assets/46ebc1ea-9c05-4b60-8378-4a69da677d5d)

**Comment by jerielng** [comment]
Hi @edapess, we are unable to reproduce this in our sample app. There were a couple of notable changes in React Native 0.76, namely that the New Architecture is now enabled by default. One thing to note is that the `pod install` semantics have [changed](https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here#opt-out), which can have implications on how you build your project. Could you verify which architecture your application is using, and check which command you are using to `pod install`?

Additionally, there are often other parallel dependencies you may need to upgrade in your `package.json` when updating your project to the latest version. This can often lead to incompatibilities and consequently build failures if they aren't upgraded together. You can use this helpful community [tool](https://react-native-community.github.io/upgrade-helper/) to determine which other dependencies you may need to upgrade.

If you are still facing issues, please feel free to write in to support@braze.com and reference this GitHub issue. Thanks!

**Comment by edapess** [comment]
@jerielng I know about upgrade helper, also I tried install pods with both old/new architecture, let me remove all my node modules, caches, cz I had many issues related to other packages, and the last one (maybe) is the error above that i mentioned.

let me check again and get back to this thread :)))

**Comment by edapess** [comment]
@jerielng So I build IOS with old architecture, but on Android I'm getting this 
![Screenshot 2024-10-31 at 10 50 07 AM](https://github.com/user-attachments/assets/37c9d21c-25b2-499c-9f0a-6903abe4c766)

**Comment by mobinni** [comment]
I am facing similar errors when building on 0.76

<img width="440" alt="Screenshot 2024-10-31 at 9 02 18 AM" src="https://github.com/user-attachments/assets/33f7fefc-107d-4804-be0a-ba4d8b45fda1">

**Comment by jerielng** [comment]
@edapess @mobinni Could you both write in to support@braze.com with further details about your projects:
* Full list of reproduction steps (commands used to install)
* A copy of your `package.json` file
* Which React Native architecture you are using (legacy or New Architecture)
* Any other relevant information

and they will be able to help you troubleshoot and diagnose the issue? Thanks!

**Comment by mobinni** [comment]
I'm not sure I can provide that information, however what I can provider:

I have tried on 0.75.6 and 0.76.1 new architecture, same issue arises. I will try to put together a demo app with the issue. I do see the Braze sample app on this repo is still on 0.71

**Comment by jerielng** [comment]
@mobinni I believe the `package.json` you are looking at is for the SDK, which uses `0.71.0` as a minimum but does not lock users to that specific version.

The `package.json` for our public sample app [is currently using 0.75.2](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/package.json), but we have internally tested with `0.76.1` without being able to reproduce these build errors on either Android or iOS for either architecture of React Native. You may use this updated file as a cross-reference: [package.json](https://github.com/user-attachments/files/17588497/package.json)

**Comment by edapess** [comment]
@mobinni i built successfully with old architecture (0.76), you have to remove Podfile.lock, clean cache, derived data and after install pods using old arch. - `RCT_NEW_ARCH_ENABLED=0 bundle exec pod install`


I will try today again with new architecture

**Comment by edapess** [comment]
@jerielng I think it's related to this https://github.com/CocoaPods/CocoaPods/issues/12105, also tommorow i will write to support

**Comment by hosseintalebi** [comment]
I'm running into a similar issue. I'm trying to run the app on the new architecture:
- @braze/react-native-sdk@12.1.0
- react-native@0.74.6

![image](https://github.com/user-attachments/assets/27461d8b-13d8-4d3e-84ab-040ae25576a5)

**Comment by alzalabany** [comment]
Same issue, not able to use when new arch =true

**Comment by jerielng** [comment]
@hosseintalebi @alzalabany Could you cross-reference your package.json with the one linked [here](https://github.com/braze-inc/braze-react-native-sdk/issues/273#issuecomment-2449890158) and verify if there are any mismatching React Native dependencies? For a deeper investigation into your project, we would recommend reaching out to our support team at support@braze.com to debug the issue further. Thanks!

**Comment by QSuraj** [comment]
+1 

#### Facing same issue on 0.76.1 -
<img width="296" alt="image" src="https://github.com/user-attachments/assets/d63d9c04-c5f5-4c43-b910-9ff70e8b61da">

**Comment by jerielng** [comment]
@QSuraj Likewise, could you also write in to support@braze.com with further details of your integration, as mentioned above? We would like to understand the common thread behind these build errors to further diagnose them as we are not able to reproduce them from our end. Thanks!

**Comment by alzalabany** [comment]
In braze repo new arch is disabled.
Please either use a new Reactnative project or enable newarch and issue should be reproduced on android

**Comment by sircelsius** [comment]
Hi everyone. 

To clarify that we do have `newArchEnabled=true` in [`gradle.properties`](https://github.com/braze-inc/braze-react-native-sdk/blob/master/BrazeProject/android/gradle.properties#L35).

Given that we have not been able to reproduce this issue with the currently provided reproduction steps, we suggest that if you were not able to address the issue you contact support@braze.com where we will be able to ask for more information relative to your exact environment.

**Comment by msalcala11** [comment]
This might be helpful: https://github.com/zoontek/react-native-bootsplash/discussions/657#discussioncomment-11417484
