### ISSUE TITLE
[Bug]: Braze.getContentCards() - sometimes it takes a lot of time to end when called too often

### ISSUE THREAD

**Issue by wojcik92michal** [braze-inc/braze-react-native-sdk#274]
### Which Platforms?

iOS

### Which React Native Version?

0.72.12

### Which @braze/react-native-sdk SDK version?

Tested on 12.2.0 and 13.1.1

### Repro Rate

From time to time

### Steps To Reproduce

Example:
```
import Braze from "@braze/react-native-sdk"

  useEffect(() => {
    const timeout = setInterval(async () => {
      await Braze.getContentCards()
    }, 10000)

    return () => {
      clearInterval(timeout)
    }
  }, [])

```

### Expected Behavior

Braze.getContentCards() ends in the reasonable time 

### Actual Incorrect Behavior

Braze.getContentCards() might take quite a lot of time. See the image - "diff" indicates how long did it take to finish the action (it is generated based on the code from "Steps to Reproduce"

![image](https://github.com/user-attachments/assets/15389335-71ac-4609-9283-a1f83bd24dc3)

### Additional Information

I know the reproduction example is the extreme one, but in my production app I was able to spot the same issue as well (but less frequently).

In our case, the production mobile app calls `getContentCards()` on startup phase. We have the limitation for calling it no often than 1 per minute, but still the problem might happen from time to time.

Do you suggest to call it even less frequent (e.g. only once per 1 minute)?

**Comment by jerielng** [comment]
Hey @wojcik92michal, do you happen to have any verbose logs from the Braze SDK that you can share, specifically whenever a call to `getContentCards` is made? Could you write in to our support team at support@braze.com and reference this GitHub issue to get a closer look at your integration and reproduction of this scenario?

**Comment by vanessaland** [comment]
Closing out this issue due to inactivity.

If you would need further assistance, feel free to reach out to our support team at [support@braze.com](mailto:support@braze.com).

Thank you!
