### ISSUE TITLE
[Bug]: Braze IOS value send to dashboard error

### ISSUE THREAD

**Issue by denison0918** [braze-inc/braze-react-native-sdk#275]
### Which Platforms?

iOS

### Which React Native Version?

6.3.1

### Which @braze/react-native-sdk SDK version?

5.2.0

### Repro Rate

100%

### Steps To Reproduce

1. braze react native -> install
2. web script -> string_number = '1', parse_int => parseInt(1), number_value => Number(1) script tag write
3. send braze

### Expected Behavior

dashboard 
-> string_number : '1'
-> parse_int : 1
-> number_value : 1

### Actual Incorrect Behavior

dashboard
-> parse_int : true
-> numbe_value : true

**Comment by denison0918** [comment]
add -> value send zero(0)  >> dashboard list 'false'

**Comment by jerielng** [comment]
Hi @denison0918, could you clarify which method(s) of the Braze SDK you are calling in your web script that you are passing these numerical values into?

**Comment by denison0918** [comment]
> Hi @denison0918, could you clarify which method(s) of the Braze SDK you are calling in your web script that you are passing these numerical values into?

Hi..~ image add
why result?? I don't know.. I feel value 2 ,... 0 / 1 -> false / true result

![braze-result](https://github.com/user-attachments/assets/8067dbd2-df2b-4f7e-9e17-926014878b33)
![braze-version](https://github.com/user-attachments/assets/2352cab3-1f52-49db-a693-d3c6de2532ff)
![braze-source](https://github.com/user-attachments/assets/aee247cc-9218-455e-b0d9-75f6802710da)

**Comment by denison0918** [comment]
![braze-testsource](https://github.com/user-attachments/assets/42b6c7b6-e720-4e7c-b70b-e20c66f07ca9)
braze test-source [WEB SOURCE] -> send -> app source -> dashboard

**Comment by jerielng** [comment]
@denison0918 It looks like you are using 5.2.0, which is an older version. Are you able to reproduce this on the latest version (13.1.1)?

**Comment by denison0918** [comment]
@jerielng Am...I updated using the command below before building.
[command :" npm update @braze/react-native-sdk --save" >> execute >> ios folder move >> "pod update braze-react-native-sdk" ]

If I use that command, will it know the latest one?

**Comment by denison0918** [comment]
I used that command and the Podlist.lock file was automatically updated.
Is 5.2 an old version??

**Comment by jerielng** [comment]
@denison0918 If you're facing issues updating the package through NPM, please write in to our support team at support@braze.com and reference this GitHub issue to get a deeper look at your integration. Thanks!

**Comment by vanessaland** [comment]
Closing out this issue due to inactivity. 

If you would need further assistance, feel free to reach out to our support team at [support@braze.com](mailto:support@braze.com). 

Thank you!
