### ISSUE TITLE
Confusing Release notes for 13.x

### ISSUE THREAD

**Issue by luke-bryant-unmind** [braze-inc/braze-react-native-sdk#277]
The release notes for 13.0.0 warn not to upgrade to this version because of a problem with unsubscribes.
https://github.com/braze-inc/braze-react-native-sdk/releases/tag/13.0.0

Subsequent releases don't seem to indicate that the problem was fixed, but there is no warning. Is it safe to upgrade to 13.1.1 or should we stay on 12.x?

**Comment by jerielng** [comment]
Hey @luke-bryant-unmind, this issue has been resolved in 13.1.0 and up, so any version past 13.0.0 should be safe. This was part of the underlying Braze Swift SDK, so the linked release notes for those versions should provide more details on that.
