### ISSUE TITLE
[Feature]: Document BrazeIdentityError error code 28

### ISSUE THREAD

**Issue by luke-bryant-unmind** [braze-inc/braze-react-native-sdk#278]
### What problem are you facing?

I'm seeing this error from the sdk:

```
BrazeIdentityError
Failed to authenticate Braze SDK request. Error Code: 28
```

I can't find any documentation about what Error Code: 28 refers to.

### Workarounds

Ignore the error code

**Comment by jerielng** [comment]
Hey @luke-bryant-unmind, you can find the full list of SDK authentication error codes [here](https://www.braze.com/docs/developer_guide/authentication/#error-codes) as well as further details about SDK authentication on the rest of that page.

**Comment by jerielng** [comment]
Closing out this issue as resolved - feel free to reach back out if you have further questions. Thank you!
