### ISSUE TITLE
Trigger IAM ready from JS

### ISSUE THREAD

**Issue by ahanriat** [braze-inc/braze-react-native-sdk#63]
**Affects:** iOS & Android

## Problem

When using **InAppMessaging** with Braze on a **fresh start**, there is **a gap** where the user can press a deep-link present on the IAM, while the JS is still not completely ready. This is particularly easy to reproduce with a large JS codebase or a long loading (waiting for a response from backend for example).

➡️ This result in the loss of the deep link  😢 😢 😢 

## Potential solution

One solution would be to pause all IAM while the JS is not ready and call an `Appboy.isReady()` from the JS side when we are ready to handle deep link 🤗 

## Context

We've already talked to Braze support about this issue. I'm adding their response here for more context.

From Braze support ❤️ :

```
Hi all,

Happy Friday! Just jumping in here with some additional information. It looks like this behaviour is easier to reproduce when there’s a large amount of JS on a less performant phone.

As far as we can tell from your implementation, you are already handling this with a workaround but we believe the best solution might be to build a native IAM manager listener that holds on to all IAMs until receiving a signal from JS that the JS is loaded and IAMs can be displayed [that way you don't need to delay init or disable]. Ideally, we would have an out of the box callback for "IAMs ready" - we have added this as an enhancement request and will work to implement this in the future.

Let me know if you have any follow up questions or concerns on this.

Kind regards,
```

**Comment by hokstuff** [comment]
Hi @ahanriat,

Apologies for reviving an old thread, but are you still experiencing issues on the latest release?

**Comment by hokstuff** [comment]
I'm closing out this thread due to inactivity and possible staleness. Feel free to reach out to support@braze.com if you still have concerns - thanks!
