### ISSUE TITLE
Background crash upon receiving push notification (calling startHeadlessTask)

### ISSUE THREAD

**Issue by MihailoCherryz** [braze-inc/braze-react-native-sdk#96]
In the last few months we've been seeing an increase in the number of background crashes when the device receives push notifications from Braze (Braze is the only source of push notifications).
We've observed this error in Firebase and Sentry, and it is logged with the following:

```ExceptionsManagerModule.java line 83```
```com.facebook.react.modules.core.ExceptionsManagerModule.reportException```
```Invariant Violation: Module AppRegistry is not a registered callable module (calling startHeadlessTask)```

Users still receive the notification and seem to be able to open it.
This crash makes up the majority of our observed crashes, and is clustered around the time when we do major push notification campaigns on Braze. We would like to resolve it.

Thank you in advance.

This is Android only.

Dependencies that we use are listed below:

```
"@react-native-firebase/analytics": "7.6.8",
"@react-native-firebase/app": "8.4.6",
"@react-native-firebase/crashlytics": "8.4.10",
"@react-native-firebase/messaging": "7.9.1",
"@react-native-firebase/perf": "7.4.9",
"@sentry/react-native": "1.9.0",
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-appboy-sdk": "1.24.0",
"react-native-branch": "5.0.0",
"react-native-navigation": "7.3.0",
```
```
Android Studio 4.1.1
Java v11
Node v10.16.0
npm v6.13.7
```

Gradle:
```
ext {
    buildToolsVersion = "29.0.2"
    minSdkVersion = 21
    compileSdkVersion = 29
    targetSdkVersion = 29
    androidXAnnotation = "1.1.0"
    androidXBrowser = "1.2.0"
    androidXCore = "1.3.2"
    googlePlayServicesAuthVersion = "18.1.0"
    kotlinVersion = "1.3.72"
    RNNKotlinVersion = kotlinVersion
    RNNKotlinStdlib = "kotlin-stdlib-jdk8"
}
dependencies {
    classpath 'com.android.tools.build:gradle:3.6.4'
    classpath 'com.google.firebase:perf-plugin:1.3.1'
    classpath 'com.google.gms:google-services:4.3.4'
    classpath 'io.fabric.tools:gradle:1.28.0'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
}
```

**Comment by hokstuff** [comment]
Hi @MihailoCherryz,

Are you still experiencing these issues on the latest SDK version?

**Comment by hokstuff** [comment]
I'm closing out this thread due to inactivity and possible staleness. Feel free to reach out to support@braze.com if you still have concerns - thanks!
