### ISSUE TITLE
Clarification on populateInitialUrlFromLaunchOptions

### ISSUE THREAD

**Issue by mlazari** [braze-inc/braze-react-native-sdk#98]
In the example project `populateInitialUrlFromLaunchOptions` call happens after React Native bridge initialization: https://github.com/Appboy/appboy-react-sdk/blob/1.25.0/AppboyProject/ios/AppboyProject/AppDelegate.m#L59

I encountered an issue with that when `ReactAppboy.getInitialURL()` is being called early from js code and the link is not populated yet by `populateInitialUrlFromLaunchOptions`. Moving `populateInitialUrlFromLaunchOptions` above RN bridge initialization fixed the issue for me. Does it make sense to specify this in [documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/ios/sdk_integration/#ios-completing-the-integration)? Also is `ReactAppboy.getInitialURL()` documented anywhere? I only found it in the example project.

**Comment by hokstuff** [comment]
Hi @mlazari,

Are you still experiencing this issue?

**Comment by mlazari** [comment]
@hokstuff No, moving the `populateInitialUrlFromLaunchOptions` call fixed it.
